### PR TITLE
Update French.js

### PR DESCRIPTION
**Pull request by jimmyr57000**
There are a lot of incomprehensible words or phrases.
I will do a new update later!
There is still a lot to fix!

### CODE REVIEW

**Comment by Ferks-FK** [comment]
I figured there might be things wrong, translators don't always get it right.
Thanks for the help, as soon as I'm done, I'll merge it.

**Comment by Ferks-FK** [comment]
@jimmyr57000 Hello, do you still intend to correct the French language?

**Comment by jimmyr57000** [comment]
Hello, Of course!
There is not a lot of error but there is a little left!

**Comment by Ferks-FK** [comment]
> Hello, Of course! There is not a lot of error but there is a little left!

Ok, I'm waiting 😁

**Comment by Ferks-FK** [comment]
Due to inactivity, this PR has been closed.

**Pull request closed without merging**
